DROP TABLE IF EXISTS TBL_TASK;

CREATE TABLE TBL_TASK (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    task_name VARCHAR(250) NOT NULL,
    task_description VARCHAR(250) NOT NULL,
    employee_id INT
);

DROP TABLE IF EXISTS TBL_EMPLOYEE;

CREATE TABLE TBL_EMPLOYEE (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    email VARCHAR(250) DEFAULT NULL
);

CREATE TABLE TBL_SCOPE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255)
);

-- Columna y FK hacia scope
ALTER TABLE TBL_TASK ADD COLUMN id_scope INT;

ALTER TABLE TBL_TASK
  ADD CONSTRAINT fk_task_scope
  FOREIGN KEY (id_scope) REFERENCES TBL_SCOPE(id);
  